### ISSUE TITLE
‘forall’ may become a keyword

### ISSUE THREAD

**Issue by int-index** [jwaldmann/haskell-obdd#13]
This library defines `forall` as an identifier. The GHC Proposal [#281 “Visible forall”](https://github.com/ghc-proposals/ghc-proposals/pull/281) proposes to make `forall` a keyword, so it will no longer be a valid identifier. The proposal is currently under consideration by the GHC Steering Committee and is recommended for acceptance.

The solution is to use `forAll`, `forall_`, or any other name instead. We are currently considering various migration options (e.g. a warning for 3 releases before making the change) and would love to get input from library maintainers. Please share your thoughts at https://github.com/ghc-proposals/ghc-proposals/discussions/440.

Thanks!

**Comment by jwaldmann** [comment]
Thanks for alerting me. Yes, I can switch to `for_all`. I leave this issue here open to remind me.
